/* eslint-disable @typescript-eslint/restrict-template-expressions */
import { type NextPage } from "next";
import { DashboardFooter } from "~/components/DashboardElements/components/DashboardFooter/DashboardFooter";
import { DashboardWrapper } from "~/components/DashboardWrapper/DashboardWrapper";
import Link from "next/link";
import styles from "./index.module.scss";
import Head from "next/head";
import { UiBox } from "~/components/uiBox/uiBox";
import { useState } from "react";
import { Button } from "~/components/button/button";

type Benefit = {
  name: string;
  price: number;
  image: string;
};

const GetBenefits: NextPage = () => {
  const [showModal, setShowModal] = useState(false);
  const [activeBenefit, setActiveBenefit] = useState<Benefit>();
  return (
    <>
      <Head>
        <title>Get benefits | Parky</title>
        <meta name="Benefits page" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <>
        <div
          className={
            showModal && activeBenefit
              ? styles.modalWrapper
              : // eslint-disable-next-line @typescript-eslint/restrict-template-expressions
                `${styles.modalWrapper} ${styles.modalHidden}`
          }
        >
          <section>
            <h4>Claim benefit</h4>
            <p>{`Are you sure you want to claim a ${activeBenefit?.name} for ${activeBenefit?.price} Parcoins?`}</p>
            <div className={styles.buttonWrapper}>
              <Button
                onClick={() => setShowModal(false)}
                text="Cancel"
                type="secondary"
              />
              <Button
                onClick={() => console.log("claimed")}
                text="Claim"
                type="primary"
              />
            </div>
          </section>
        </div>
        <DashboardWrapper active="get-benefits">
          <>
            <div className={styles.contentWrapper}>
              <h2>Get benefits</h2>
              <UiBox>
                <h4>Refund Parcoin</h4>
                <p>BALANCE HERE</p>
                <p>REFUND</p>
              </UiBox>
              <UiBox>
                <h4>Available benefits</h4>
                <section className={styles.benefitsWrapper}>
                  <article className={styles.benefitItem}>
                    <div>IMAGE</div>
                    <p>Benefit name</p>
                    <p>Price</p>
                    <p
                      onClick={() => {
                        setShowModal(true);
                        setActiveBenefit({
                          name: "cool benefit",
                          price: 250,
                          image: "XD",
                        });
                      }}
                    >
                      GET
                    </p>
                  </article>
                  <article className={styles.benefitItem}>
                    <div>IMAGE</div>
                    <p>Benefit name</p>
                    <p>Price</p>
                    <p>GET</p>
                  </article>
                  <article className={styles.benefitItem}>
                    <div>IMAGE</div>
                    <p>Benefit name</p>
                    <p>Price</p>
                    <p>GET</p>
                  </article>
                  <article className={styles.benefitItem}>
                    <div>IMAGE</div>
                    <p>Benefit name</p>
                    <p>Price</p>
                    <p>GET</p>
                  </article>
                  <article className={styles.benefitItem}>
                    <div>IMAGE</div>
                    <p>Benefit name</p>
                    <p>Price</p>
                    <p>GET</p>
                  </article>
                  <article className={styles.benefitItem}>
                    <div>IMAGE</div>
                    <p>Benefit name</p>
                    <p>Price</p>
                    <p>GET</p>
                  </article>
                </section>
              </UiBox>
              <DashboardFooter>
                <ul>
                  <li>
                    <Link href="/contact">Contact</Link>
                  </li>
                  <li>
                    <Link href="/help">Help</Link>
                  </li>
                </ul>
              </DashboardFooter>
            </div>
          </>
        </DashboardWrapper>
      </>
    </>
  );
};

export default GetBenefits;
